# -*- coding: utf-8 -*-
"""Iot Predictive Maintenance Engine Project week1 & 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R70RbtkcniO1ZiUqddGk9YGdaY-_O4jw

Project Title: IoT Predictive Maintenance Engine.
Product Brand Name: "FactoryGuard AI"
"""

import pandas as pd

df = pd.read_csv('ai4i2020.csv')
df.head()

"""1. LOADING AND EXPLORING THE DATA

     Imports the data (ai4i2020.csv) using pandas.read_csv.
     
     Checks the size, columns, data types, and any missing values.

** WEEK-1 :DATA EXPLORATION
           
           The Process of examining a dataset to understand its main characterstics, structure, and contents.


*   df.shape: It returns thedimensions of dataset as a tuple.This helps in understanding the size of data.
*   df.coloums: List of all coloums name in the Dataframe.
*   df.info(): Displays a concise summary of the DataFrame'
*   df.isnull().sum(): Calculates the total number of missing (null) values per column.

DATASET OVERVIEW
**  The dataset comprises machine sensor readings, including air temperature, process temperature, rotational speed, torque, and tool wear, which are used to monitor machine operation.
"""

# Rename columns for clarity
df = df.rename(columns={
    'Air temperature [K]': 'air_temp_k',
    'Process temperature [K]': 'process_temp_k',
    'Rotational speed [rpm]': 'rotational_speed',
    'Torque [Nm]': 'torque',
    'Tool wear [min]': 'tool_wear',
    'Machine failure': 'machine_failure'
})

# Convert temperatures from Kelvin to Celsius
df['air_temp_c'] = df['air_temp_k'] - 273.15
df['process_temp_c'] = df['process_temp_k'] - 273.15

# Drop original Kelvin columns
df.drop(['air_temp_k', 'process_temp_k'], axis=1, inplace=True)

# Show the structure and a sample of the data
print("Data types and info:")
print(df.info())
print("\nFirst few rows:")
print(df.head())

# Optional: Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

"""DATA CLEANING

**  During the data cleaning phase, column names were simplified for clarity, and temperature measurements were converted from Kelvin to Celsius, enhancing interpretability. With these adjustments, the dataset is prepared for feature analysis.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select only numeric columns for correlation analysis
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Calculate the correlation matrix
corr_matrix = numeric_df.corr()

# Display the correlation matrix
print(corr_matrix)

# Plot the correlation matrix as a heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Sensor Data')
plt.show()

"""Correlation Analysis
**  I was generated to analyze the relationships between sensor variables and machine failure.
The heatmap visualization helps identify which features are positively or negatively correlated with failure.

"""

# ----- FEATURE ENGINEERING (Lag + Rolling) -----

sensor_cols = [
    'rotational_speed',
    'torque',
    'tool_wear',
    'air_temp_c',
    'process_temp_c'
]

# Create lag features (t-1, t-2)
for col in sensor_cols:
    df[f'{col}_t-1'] = df[col].shift(1)
    df[f'{col}_t-2'] = df[col].shift(2)

# Create rolling statistics (window = 3)
for col in sensor_cols:
    df[f'{col}_roll_mean_3'] = df[col].rolling(window=3).mean()
    df[f'{col}_roll_std_3'] = df[col].rolling(window=3).std()

# Drop rows with NaN values created due to lag/rolling
df.dropna(inplace=True)

print("Feature engineering completed successfully")
print(df.head())

"""FEATURE EXTRACTION
** Lag and rolling window features are engineered to capture temporal dependencies and recent trends in the sensor data. Lag features reflect past sensor values, while rolling features summarize recent sensor behavior, both of which can help machine learning models detect patterns leading up to machine failure.
"""

# Split the data in order of time to avoid data leakage
X = df.drop('machine_failure', axis=1)
y = df['machine_failure']

# Find the index to split at 80%
split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]
y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

print(f"Train size: {X_train.shape[0]}, Test size: {X_test.shape[0]}")

"""TRAIN - TEST SPLIT DATASET

**  It is the process of dividing your dataset into two parts: one for training your machine learning model (train), and another for evaluating its performance on unseen data (test).
"""

# Drop non-numeric / identifier columns
columns_to_drop = ['Product ID', 'Type']

X_train_model = X_train.drop(columns=columns_to_drop)
X_test_model  = X_test.drop(columns=columns_to_drop)

"""DATA LEAKAGING

** It occurs when the training data includes information that would not be available at prediction time, such as data from the future or from the target variable.

MODELLING

** The process of creating a machine learning model that can learn from data and make predictions or classifications.

HYPERPARAMETER TUNING

** The process of finding the best set of parameters that control how your machine learning model learns(such as the number of trees in a forest, learning rate, or tree depth).
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, f1_score, recall_score

# Identify non-numeric columns that need to be dropped from X_train and X_test
columns_to_drop_from_X = ['Product ID', 'Type']

# Drop these columns from X_train and X_test before training
X_train_processed = X_train.drop(columns=columns_to_drop_from_X)
X_test_processed = X_test.drop(columns=columns_to_drop_from_X)

# Train a baseline Random Forest
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_processed, y_train)
y_pred_rf = rf.predict(X_test_processed)

# Evaluate
print("Random Forest Results:")
print(classification_report(y_test, y_pred_rf, digits=4))
print("F1-score:", f1_score(y_test, y_pred_rf))
print("Recall:  ", recall_score(y_test, y_pred_rf))

"""RANDOM FOREST

** It is an ensemble learning method that builds multiple decision trees during training and merges their predictions to get a more accurate and stable prediction.

CLASSIFICATION REPORT

** It includes precision, recall, F1-score, and support for each class, providing a quick overview of how well the model performed on different categories.

"""

from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [50, 100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [3, 5, 7, 10],
    'gamma': [0, 0.1, 0.3, 0.5],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0]
}

columns_to_drop = ['Product ID', 'Type']

X_train_model = X_train.drop(columns=columns_to_drop)
X_test_model  = X_test.drop(columns=columns_to_drop)

xgb = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

search = RandomizedSearchCV(
    xgb,
    param_distributions=param_dist,
    n_iter=20,
    scoring='f1',
    n_jobs=-1,
    cv=3,
    verbose=2,
    random_state=42
)

# ✅ CORRECT FIT
search.fit(X_train_model, y_train)

print("Best hyperparameters:", search.best_params_)

# ✅ CORRECT PREDICTION
y_pred_xgb = search.predict(X_test_model)

print("XGBoost Results (Optimized):")
print(classification_report(y_test, y_pred_xgb, digits=4))
print("F1-score:", f1_score(y_test, y_pred_xgb))
print("Recall:  ", recall_score(y_test, y_pred_xgb))

"""XGBoost Model with RandomizedSearchCV

** RandomizedSearchCV tunes the XGBoost hyperparameters for best F1-score (you can adjust for 'recall' scoring as needed).

** Evaluation focuses not just on accuracy, but on F1-score and recall—especially important for minimizing false negatives (catching machine failures).

** Compare the F1 and Recall of both models. Your goal is to beat the baseline Random Forest with the optimized XGBoost.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, f1_score, recall_score
from sklearn.linear_model import LogisticRegression

# Logistic Regression baseline pipeline
log_reg_pipeline = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('log_reg', LogisticRegression(
        max_iter=1000,
        class_weight='balanced',  # Important for failure imbalance
        random_state=42
    ))
])

# use numeric-only features
log_reg_pipeline.fit(X_train_model, y_train)
y_pred_lr = log_reg_pipeline.predict(X_test_model)

print("Logistic Regression Baseline Results:")
print(classification_report(y_test, y_pred_lr, digits=4))
print("F1-score:", f1_score(y_test, y_pred_lr))
print("Recall:  ", recall_score(y_test, y_pred_lr))

